### ISSUE TITLE
在线地图绘制区域不太准确

### ISSUE THREAD

**Issue by jeremyxu2010** [phodal/vmap#16]
在线地图绘制区域不太准确，比如在我选择深圳市，绘制的多边形区域实际上绘制到香港去了。
![qq20160410-0](https://cloud.githubusercontent.com/assets/752346/14408219/c294162a-ff1d-11e5-92a4-389b91d978cc.png)

**Comment by phodal** [comment]
@jeremyxu2010 这个我也没办法，地图数据是第三方绘制的。我没有足够的时间和能力去绘制这个地图，地图本身的数据量大小~=10M，光绘制这个地图至少就要一个月。
