### ISSUE TITLE
distance unit auto adjustment

### ISSUE THREAD

**Issue by sk1418** [phodal/vmap#5]
I got output:

```
离你最近的大神是 Yanhaijing 
距离: 7459152.626445884 米 
太远了? 来添加大神 V Map
```

It is not so easy to read, I meant the distance value. It would be great to automatically adjust the unit to KM if value>1000. also the precision could be chop to 2. I guess it is enough for most users...

Interesting and creative site anyway.

P.S. If you do need the most precise value, you could probably consider showing in a mouse-over Tip. I am not good at web dev, so all above is just my two cents.

**Comment by phodal** [comment]
@sk1418 OK
